version: "3.7"
services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scrumbarista
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  api:
    platform: linux/amd64
    # image: api
    build: ./api
    command: yarn start:dev
    volumes:
      - ./api/src:/app/src
      - ./api/test:/app/test
      - ./api/nest-cli.json:/app/nest-cli.json
    environment:
      - DB=db
    ports:
      - 8000:8000
    depends_on:
      - db
  # app:
  #   platform: linux/amd64
  #   build: ./app
  #   command: yarn dev
  #   volumes:
  #     - ./app/pages:/app/pages
  #     - ./app/components:/app/components
  #     - ./app/.env.local:/app/.env.local
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - api
  # bolt:
  #   platform: linux/amd64
  #   build: ./bolt
  #   command: yarn start:dev
  #   volumes:
  #     - ./bolt/src:/bolt/src
  #   environment:
  #     - SLACK_SIGNING_SECRET=ff9be4e29c27c1a5e087b68c8048d56e
  #     - SLACK_BOT_TOKEN=xoxb-1704809032615-2750821186736-T8Elda9RiWzavrCrpvR4IbWU
  #     - PORT=8080
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - api
  # marketing:
  #   platform: linux/amd64
  #   build: ./marketing
  #   command: yarn dev
  #   volumes:
  #     - ./marketing/pages:/app/pages
  #     - ./marketing/components:/app/components
  #   ports:
  #     - 4000:3000
