version: "3.7"
services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scrumbarista
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  api:
    platform: linux/amd64
    build: ./api
    command: npm run start:dev
    volumes:
      - ./api/src:/app/src
      - ./api/test:/app/test
      - ./api/nest-cli.json:/app/nest-cli.json
    environment:
      - DB_URL=mysql://username:password@db:3306/scrumbarista
    ports:
      - 8000:8000
    depends_on:
      - db
  app:
    platform: linux/amd64
    build: ./app
    command: npm run dev
    volumes:
      - ./app/pages:/app/pages
      - ./app/components:/app/components
      - ./app/.env.local:/app/.env.local
    environment:
      - SLACK_CLIENT_ID=CHANGE_ME
      - SLACK_CLIENT_SECRET=CHANGE_ME
      - NEXTAUTH_URL=CHANGE_ME
    ports:
      - 3000:3000
    depends_on:
      - api
  bolt:
    platform: linux/amd64
    build: ./bolt
    command: npm run start:dev
    volumes:
      - ./bolt/src:/bolt/src
    environment:
      - SLACK_SIGNING_SECRET=REPLACE_ME
      - SLACK_BOT_TOKEN=REPLACE_ME
      - PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - api
