apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.containers.api.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4 }}
    app: {{.Values.containers.api.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.containers.api.name}}
  replicas: {{.Values.containers.api.replicas}}
  template:
    metadata:
      labels: {{include "labels" . | nindent 8 }}
        app: {{.Values.containers.api.name}}
    spec:
      containers:
      - name: {{.Values.containers.api.name}}
        image: {{.Values.containers.api.image.repository}}:{{.Values.containers.api.image.tag}}
        imagePullPolicy: Always
        resources: {{toYaml .Values.containers.api.resources | nindent 10}}
        ports:
        - containerPort: {{.Values.containers.api.port}}
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            port: {{.Values.containers.api.port}}
            path: /health
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            port: {{.Values.containers.api.port}}
            path: /health
        env:
        {{- with .Values.containers.api.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.containers.api.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
    app: {{.Values.containers.api.name}}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.containers.api.port}}
      targetPort: {{.Values.containers.api.port}}
  selector:
    app: {{.Values.containers.api.name}}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{.Values.containers.api.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
    app: {{.Values.containers.api.name}}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: {{toYaml .Values.containers.api.hosts | nindent 6}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{.Values.containers.api.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
    app: {{.Values.containers.api.name}}
spec:
  hosts: {{toYaml .Values.containers.api.hosts | nindent 4}}
  gateways:
  - {{.Values.containers.api.name}}
  http:
  - route:
    - destination:
        host: {{.Values.containers.api.name}}
        port:
          number: {{.Values.containers.api.port}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-api-migrations
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
    app: {{.Values.containers.api.name}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-api-migrations
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: {{.Values.containers.api.name}}-migrate
        image: {{.Values.containers.api.image.repository}}:{{.Values.containers.api.image.tag}}
        imagePullPolicy: Always
        resources: {{toYaml .Values.containers.api.resources | nindent 10}}
        command: ["npm", "run", "typeorm:run"]
        env:
        {{- with .Values.containers.api.env }}
        {{- toYaml . | nindent 10 }}
        {{- end }}