apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.containers.app.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4 }}
    app: {{.Values.containers.app.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.containers.app.name}}
  replicas: {{.Values.containers.app.replicas}}
  template:
    metadata:
      labels: {{include "labels" . | nindent 8 }}
        app: {{.Values.containers.app.name}}
    spec:
      containers:
      - name: {{.Values.containers.app.name}}
        image: {{.Values.containers.app.image.repository}}:{{.Values.containers.app.image.tag}}
        imagePullPolicy: Always
        resources: {{toYaml .Values.containers.app.resources | nindent 10}}
        ports:
        - containerPort: {{.Values.containers.app.port}}
        readinessProbe:
          initialDelaySeconds: 15
          httpGet:
            port: {{.Values.containers.app.port}}
            path: /api/health
        livenessProbe:
          initialDelaySeconds: 15
          httpGet:
            port: {{.Values.containers.app.port}}
            path: /api/health
        env:
        {{- with .Values.containers.app.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.containers.app.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
    app: {{.Values.containers.app.name}}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.containers.app.port}}
      targetPort: {{.Values.containers.app.port}}
  selector:
    app: {{.Values.containers.app.name}}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{.Values.containers.app.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
    app: {{.Values.containers.app.name}}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{.Values.containers.app.host}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{.Values.containers.app.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
    app: {{.Values.containers.app.name}}
spec:
  hosts:
  - {{.Values.containers.app.host}}
  gateways:
  - {{.Values.containers.app.name}}
  http:
  - route:
    - destination:
        host: {{.Values.containers.app.name}}
        port:
          number: {{.Values.containers.app.port}}
