apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meta.name }}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.containers.bolt.port}}
      targetPort: {{.Values.containers.bolt.port}}
  selector:
    app: {{.Values.meta.name}}
