meta:
  name: api
  namespace: scrumbarista
  environment: development
containers:
  api:
    name: api
    image:
      repository: 418118555604.dkr.ecr.us-east-1.amazonaws.com/scrumbarista-api
      tag: CHANGE_ME
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
    - name: DB_URL
      value: CHANGE_ME 
    port: 8000
    replicas: 1
  bolt:
    name: bolt
    image:
      repository: 418118555604.dkr.ecr.us-east-1.amazonaws.com/scrumbarista-bolt
      tag: CHANGE_ME
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
    - name: SLACK_SIGNING_SECRET
      value: REPLACE_ME
    - name: SLACK_BOT_TOKEN
      value: REPLACE_ME
    - name: PORT
      value: "8080"
    port: 8080
    replicas: 1
  app:
    name: app
    image:
      repository: 418118555604.dkr.ecr.us-east-1.amazonaws.com/scrumbarista-app
      tag: CHANGE_ME
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    port: 3000
    replicas: 1
    host: scrumbarista-app.useast1.dev.baily.io
