meta:
  name: scrumbarista
  namespace: scrumbarista
  environment: development
containers:
  api:
    name: api
    image:
      repository: 418118555604.dkr.ecr.us-east-1.amazonaws.com/scrumbarista-api
      tag: CHANGE_ME
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: PORT
        value: "8000"
      - name: DB_URL
        valueFrom:
          secretKeyRef:
            name: app.config
            key: DB_URL
      - name: SLACK_SIGNING_SECRET
        valueFrom:
          secretKeyRef:
            name: app.config
            key: SLACK_SIGNING_SECRET
      - name: SLACK_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: app.config
            key: SLACK_BOT_TOKEN
    port: 8000
    replicas: 1
    hosts:
      - scrumbarista-api.useast1.dev.baily.io
  mysql:
    env:
      - name: HOST
        valueFrom:
          secretKeyRef:
            name: app.config
            key: HOST
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: app.config
            key: DB_USERNAME
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app.config
            key: DB_PASSWORD
  app:
    name: app
    image:
      repository: 418118555604.dkr.ecr.us-east-1.amazonaws.com/scrumbarista-app
      tag: CHANGE_ME
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: NEXT_PUBLIC_API_URL
        value: http://api.svc.cluster.local
      - name: NEXT_PUBLIC_BOLT_URL
        value: http://bolt.svc.cluster.local
      - name: SLACK_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: app.config
            key: SLACK_CLIENT_SECRET
      - name: SLACK_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: app.config
            key: SLACK_CLIENT_ID
    port: 3000
    replicas: 1
    hosts:
      - scrumbarista-app.useast1.dev.baily.io
  bolt:
    name: bolt
    image:
      repository: 418118555604.dkr.ecr.us-east-1.amazonaws.com/scrumbarista-bolt
      tag: CHANGE_ME
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: API_URL
        value: http://api.svc.cluster.local
      - name: PORT
        value: "8080"
      - name: SLACK_SIGNING_SECRET
        valueFrom:
          secretKeyRef:
            name: app.config
            key: SLACK_SIGNING_SECRET
      - name: SLACK_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: app.config
            key: SLACK_BOT_TOKEN
    port: 8080
    replicas: 1
    hosts: 
      - scrumbarista-bolt.useast1.dev.baily.io
