apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.meta.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{.Values.meta.name}}
  replicas: {{.Values.containers.marketing.replicas}}
  template:
    metadata:
      labels: {{include "labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{.Values.containers.marketing.name}}
        image: {{.Values.containers.marketing.image.repository}}:{{.Values.containers.marketing.image.tag}}
        imagePullPolicy: Always
        resources: {{toYaml .Values.containers.marketing.resources | nindent 10}}
        ports:
        - containerPort: {{.Values.containers.marketing.port}}
        readinessProbe:
          initialDelaySeconds: 15
          httpGet:
            port: {{.Values.containers.marketing.port}}
            path: /api/health
        livenessProbe:
          initialDelaySeconds: 15
          httpGet:
            port: {{.Values.containers.marketing.port}}
            path: /api/health
