apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{.Values.meta.name}}
  namespace: {{.Values.meta.namespace}}
  labels: {{include "labels" . | nindent 4}}
spec:
  hosts:
  - {{.Values.containers.api.host}}
  gateways:
  - {{.Values.meta.name}}
  http:
  - route:
    - destination:
        host: {{.Values.meta.name}}
        port:
          number: {{.Values.containers.api.port}}