name: API PR CI

on:
  pull_request:
    # paths:
    #   - "api/**"

jobs:
  api_lint_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v2

    - name: Start DB
      run: docker-compose up -d db

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Lint
      run: npm run lint

    - name: Test
      env:
        DB_URL: mysql://username:password@localhost:3306/scrumbarista
      run: |
        npm run typeorm:run 
        npm run test
        docker-compose down db
