name: API Merge CI

on:
  push:
    branches:
      - "master"
    # paths:
    #   - "api/**"

jobs:
  build:
    env:
      REGISTRY: 418118555604.dkr.ecr.us-east-1.amazonaws.com/scrumbarista-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t ${{REGISTRY}}:${{ github.sha }} bolt . 
      
      # - name: Push
      #   run: docker push ${{REGISTRY}}:${{ github.sha }}
