name: Main CI/CD

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        # Make sure you use a separate AWS user for deploying (i.e. not ADMIN)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Helm Install
        uses: ./.github/actions/helm
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: upgrade --install scrumbarista ./deploy --namespace scrumbarista --set containers.bolt.image.tag=${{ github.sha }} --atomic --wait
