name: Lint & Test

on:
  pull_request:
    branches:
      - master

jobs:
  lint_and_test_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Test
        run: make test
